<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
class Q_HOADONViewEdit extends ViewEdit
{
 public function display()
 {
     //truyền giá trị của field ticker_symbol vào tpl      
    //  $this->ss->assign("giamgia_hd", "C");
     parent::display(); // TODO: Change the autogenerated stub
 }
}